# 애플리케이션 포트 설정
server:
  port: 80

spring:
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/shop
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate

    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

# 상품 이미지 업로드 경로
itemImgLocation: /Users/taeyanglim/shop/item/

# 리소스 업로드 경로
uploadPath: file:///Users/taeyanglim/shop/


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
